package(default_visibility = ["//visibility:public"])

load("@ts_protoc_gen//:defs.bzl", "typescript_proto_library")


typescript_proto_library(
    name = "timestamp_proto_ts",
    proto = "@com_google_protobuf//:timestamp_proto",
)

